config/routes.rb
# encoding: UTF-8

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/advanced-roadmap
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

get "milestones/total_graph", :to => "milestones#total_graph"
resources :projects do
  resources :milestones, :only => [:new, :create, :index]
end
resources :milestones, :only => [:show, :edit, :update, :destroy]

app/models/milestone.rb
# encoding: UTF-8

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/advanced-roadmap
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

class Milestone < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :project
  has_many :milestone_versions, :dependent => :destroy
  has_many :versions, :through => :milestone_versions

  include Redmine::SafeAttributes
  safe_attributes :name, :description, :milestone_effective_date

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => [:project_id]
  validates_length_of :name, :maximum => 60
  validates_format_of :milestone_effective_date, :with => /\A\d{4}-\d{2}-\d{2}\z/,
                      :message => 'activerecord_error_not_a_date', :allow_nil => true
  
  def to_s
    name
  end
  
  def <=>(milestone)
    if self.milestone_effective_date
      if milestone.milestone_effective_date
        if self.milestone_effective_date == milestone.milestone_effective_date
          self.name <=> milestone.name
        else
          self.milestone_effective_date <=> milestone.milestone_effective_date
        end
      else
        -1
      end
    else
      if milestone.milestone_effective_date
        1
      else
        self.name <=> milestone.name
      end
    end
  end

  def versions?(version)
    versions.index(version) != nil
  end

  def completed?
    milestone_effective_date && (milestone_effective_date <= Date.today)
  end

  def is_a?(o)
    return true if o == Version
    super
  end

  def self.estimated_due_date(totals)
    estimated_due_date = nil
    non_working_week_days = Setting.non_working_week_days.map{ |day| day.to_i % 7 }
    if (non_working_week_days.count < 7)
      days = (totals[:parallel_rest_hours] / 8.0).ceil
      estimated_due_date = DateTime.now
      while days > 1
        days -= 1 unless non_working_week_days.include?(estimated_due_date.wday)
        estimated_due_date += 1.days
      end
    end
    return estimated_due_date
  end

end

app/models/milestone_version.rb
# encoding: UTF-8

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/advanced-roadmap
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

class MilestoneVersion < ActiveRecord::Base
  
  belongs_to :milestone
  belongs_to :version

end

app/controllers/milestones_controller.rb
# encoding: UTF-8

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/advanced-roadmap
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

require 'gruff/pie' if Object.const_defined?(:Magick)

class MilestonesController < ApplicationController
  
  menu_item :roadmap
  model_object Milestone

  before_action :find_model_object,
                :only => [:show, :edit, :update, :destroy]
  before_action :find_project_from_association,
                :only => [:show, :edit, :update, :destroy]
  before_action :find_project_by_project_id,
                :only => [:new, :create]
  before_action :authorize, :except => [:show, :total_graph]

  helper :custom_fields
  helper :projects
  helper :versions
  include CustomFieldsHelper
  include ProjectsHelper
  include VersionsHelper

  def show
    projects = {}
    @milestone.versions.each do |version|
      version.fixed_issues.each do |issue|
        if !(projects.include?(issue.project.id))
          projects[issue.project.id] = issue.project.id
        end
      end
    end
    Version.sort_versions(@milestone.versions)
    @more_than_one_project = (projects.length > 1)
    @totals = Version.calculate_totals(@milestone.versions)
  end

  def new
    @projects = Project.active.sort { |a, b| a.name.downcase <=> b.name.downcase }
    @versions = @project.versions
    @milestone = Milestone.new
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def create
    @milestone = Milestone.new(:user_id => User.current.id, :project_id => @project.id)
    @milestone.safe_attributes = params[:milestone]
    if request.post? and @milestone.save
      if params[:versions]
        params[:versions].each do |version|
          milestone_version = MilestoneVersion.new
          milestone_version.milestone_id = @milestone.id
          milestone_version.version_id = version
          milestone_version.save
        end
       end
      flash[:notice] = l(:notice_successful_create)
      redirect_to :controller => :projects, :action => :settings, :tab => 'milestones', :id => @project
    end
  rescue ActiveRecord::RecordNotFound => e
    render_404
  end

  def edit
    @projects = Project.active.sort { |a, b| a.name.downcase <=> b.name.downcase }
    @versions = @project.versions
  end

  def update
    @projects = Project.all.sort { |a, b| a.name.downcase <=> b.name.downcase }
    @versions = @project.versions
    versions_to_delete = @milestone.versions
    versions_to_add = []
    if params[:versions]
      params[:versions].each do |version|
        index = @milestone.versions.index(version)
        if index != nil
          versions_to_delete.remove(index)
        else
          versions_to_add << version
        end
      end
    end
    @milestone.safe_attributes = params[:milestone]
    versions_to_delete.each do |version|
      milestone_version = MilestoneVersion.where(:milestone_id => @milestone.id, :version_id => version.id).first
      milestone_version.destroy
    end
    versions_to_add.each do |version|
      milestone_version = MilestoneVersion.new
      milestone_version.milestone_id = @milestone.id
      milestone_version.version_id = version
      milestone_version.save
    end
    flash[:notice] = l(:notice_successful_update)
    redirect_to :controller => :projects, :action => :settings, :tab => 'milestones', :id => @project
  end

  def destroy
    @milestone.destroy
    redirect_to :controller => :projects, :action => :settings, :tab => 'milestones', :id => @project
  rescue
    flash[:error] = l(:notice_unable_delete_milestone, :milestone_label => milestone_label)
    redirect_to :controller => :projects, :action => :settings, :tab => 'milestones', :id => @project
  end

  def total_graph
    if Object.const_defined?(:Magick)
      g = Gruff::Pie.new(params[:size] || '500x400')
      g.hide_title = true
      g.theme = graph_theme
      g.margins = 0

      versions = params[:versions] || []
      percentajes = params[:percentajes] || []
      i = 0
      while i < versions.size and i < percentajes.size
        percentajes[i] = percentajes[i].to_f
        g.data(versions[i], percentajes[i])
        i += 1
      end

      headers['Content-Type'] = 'image/png'
      send_data(g.to_blob, :type => 'image/png', :disposition => 'inline')
    end
  end

private

  def graph_theme
    {
      :colors => ['#DB2626', '#6A6ADB', '#64D564', '#F727F7', '#EBEB20', '#303030', '#12ABAD',
                  '#808080', '#B7580B', '#316211'],
      :marker_color => '#AAAAAA',
      :background_colors => ['#FFFFFF', '#FFFFFF']
    }
  end

end

app/views/common/_advanced_roadmap_footer.html.erb
<%= javascript_tag do %>
  $(document).ready(function() {
    <%- link = link_to('Advanced roadmap',
                       Redmine::Plugin::registered_plugins[:advanced_roadmap].url)
        author = Redmine::Plugin::registered_plugins[:advanced_roadmap].author
        copy_right = link_to('©', 'http://creativecommons.org/licenses/by-nd/4.0/')
        legend = "Powered by #{link} plugin #{copy_right} 2009-2015 #{author}" -%>
    $("#footer").append('<div class="bgl"><div class="bgr"><%= raw legend %></div></div>');
  });
<% end %>

app/views/hooks/_milestones.html.erb
<%- if !@project.nil? -%>
<h3><%= label_milestone_plural %></h3>
<%- @project.milestones.sort.each do |milestone| -%>
<%= link_to_milestone(milestone) %><br />
<%- end -%>
<%- end -%>

app/views/hooks/_stylesheet.html.erb
<%= stylesheet_link_tag('advanced_roadmap', :plugin => 'advanced_roadmap', :media => 'all') %>

app/views/hooks/calendars/_milestones.html.erb
<script language="javascript">
  function AddMilestoneToDay(milestoneName, milestoneUrl, day, week)
  {
    var cellElement = null;
    var weekElement = $('.cal').find('td.week-number').filter(':contains("' + week + '")').first();
    if (weekElement)
    {
      var dayElement = weekElement.parent().find('p.day-num').filter(':contains("' + day + '")').first();
      if (dayElement)
      {
        cellElement = dayElement.parent();
      }
    }
    if (cellElement != null)
    {
      var link = document.createElement("a");
      link.innerHTML = milestoneName;
      link.href = milestoneUrl;
      var milestone = document.createElement("span");
      milestone.className = "icon icon-milestone calendar-milestone";
      milestone.appendChild(link);
      cellElement.append(milestone);
    }
  }
  <%- if milestones and milestones.any? -%>
    <%- milestones.each do |milestone| -%>
      AddMilestoneToDay("<%= milestone[:name] %>", "<%= milestone[:url] %>",
                        <%= milestone[:day] %>, <%= milestone[:week] %>);
    <%- end -%>
  <%- end -%>
</script>

<%= render :partial => 'common/advanced_roadmap_footer' %>

app/views/hooks/issues/_show.html.erb
<%= issue_fields_rows do |rows|
  milestones = @issue.fixed_version ? @issue.fixed_version.milestones.sort : []
  milestones = milestones.collect {|m| link_to(m.name, {:controller => :milestones, :action => :show, :id => m.id})}.join(', ').html_safe
  rows.left label_milestone_plural, milestones, :class => 'milestones'

  if @issue.rest_hours > 0 and
     User.current.allowed_to?(:view_time_entries, @project) and
     User.current.allowed_to?(:view_issue_estimated_hours, @project)
    rows.right l(:label_roadmap_due_in, ''), l_hours(@issue.rest_hours), :class => 'rest_hours'
  end
end %>

<%= render :partial => 'common/advanced_roadmap_footer' %>

app/views/milestones/_form.html.erb
<%= error_messages_for 'milestone' %>

<div class="box tabular">
  <p><%= f.text_field :name, :size => 60, :required => true %></p>
  <p><%= f.text_field :description, :size => 60 %></p>
  <p>
    <%= f.text_field :milestone_effective_date, :size => 10, :label => l(:field_effective_date) %>
    <%= calendar_for('milestone_milestone_effective_date') %>
  </p>
  <p>
    <label for="milestone_project_selector"><%= l(:field_project) %></label>
    <select id="project_selector">
      <% @projects.each do |project| %>
        <option<%= (project == @project) ? ' selected' : '' %> id="<%= project.id %>"><%= h(project.name) %></option>
      <% end %>
    </select>
    <%= javascript_tag :defer => 'defer' do %>
      function project_changed()
      {
        object = window.document.getElementById("project_selector");
        if (object)
        {
          if (object.selectedIndex != -1)
          {
            project_id = object.options[object.selectedIndex].id;
            <%- @projects.each do |project| -%>
              project_div = window.document.getElementById("project_<%= project.id %>_versions");
              if (project_div)
              {
                project_div.style.display = "none";
                project_div.style.visibility = "hidden";
              }
            <%- end -%>
            project_div = window.document.getElementById("project_" + project_id + "_versions");
            if (project_div)
            {
              project_div.style.display = "";
              project_div.style.visibility = "";
            }
          }
        }
      }
      jQuery(function($)
      {
        $("#project_selector").change(project_changed);
      })
    <% end %>
  </p>
  <% @projects.each do |project| %>
    <div id="project_<%= project.id %>_versions"
      <%- if (@project != project) -%>
        style="display: none; visibility: hidden;"
      <%- end -%>
    >
      <table class="list">
        <thead>
          <th style="text-align: left;"><%= l(:field_version) %></th>
          <th style="text-align: center;"><%= l(:field_effective_date) %></th>
          <th style="text-align: left;"><%= l(:field_description) %></th>
          <th style="text-align: center;"><%= label_milestone_plural %></th>
        </thead>
        <% project.versions.sort.each do |version| %>
          <tr class="<%= cycle('odd', 'even') %>">
            <td style="text-align: left;">
              <%= check_box_tag 'versions[]', version.id, @milestone.versions?(version) %>
              <%= link_to(h(version.name), :controller => :versions, :action => :show, :id => version) %>
            </td>
            <td style="text-align: center;"><%= version.effective_date %></td>
            <td style="text-align: left;"><%= version.description %></td>
            <td style="text-align: center;">
              <%= version.milestones.collect {|m| link_to(h(m.name), :controller => :milestones, :action => :show, :id => m.id) }.join(', ').html_safe %>
            </td>
          <tr>
        <% end %>
      </table>
    </div>
  <% end %>
</div>

app/views/milestones/edit.html.erb
<h2><%= label_milestone %></h2>

<%= labelled_form_for(@milestone) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f}) %>
  <%= submit_tag(l(:button_save)) %>
<% end %>

<%= render :partial => 'common/advanced_roadmap_footer' %>

app/views/milestones/new.html.erb
<h2><%= l(:label_milestone_new, :milestone_label => label_milestone) %></h2>

<%= labelled_form_for([@project, @milestone]) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f}) %>
  <%= submit_tag(l(:button_create)) %>
<% end %>

<%= render :partial => 'common/advanced_roadmap_footer' %>

app/views/milestones/show.html.erb
<div class="contextual">
  <%= link_to(l(:button_edit), edit_milestone_path(@milestone),
              :class => 'icon icon-edit') if User.current.allowed_to?(:manage_milestones, @project) %>
</div>

<h2><%= h(@milestone.name) %></h2>

<% if @milestone.completed? %>
  <p><%= format_date(@milestone.milestone_effective_date) %></p>
<% elsif @milestone.milestone_effective_date %>
  <p>
    <strong>
      <%= due_date_distance_in_words(@milestone.milestone_effective_date) %>
    </strong>
    (<%= format_date(@milestone.milestone_effective_date) %>)
  </p>
<% end %>

<p><%= h(@milestone.description) %></p>

<% if @milestone.versions.empty? %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
<div id="roadmap">
<%= render(:partial => 'versions/total', :locals => {:project => @project, :totals => @totals, :versions => @milestone.versions}) %>
<% @milestone.versions.each do |version| %>
  <h3 class="version"><%= tag 'a', :name => version.name %><%= link_to_version version %></h3>
  <%- if Redmine::VERSION::STRING < '3.4.0' -%>
    <%= render :partial => 'versions/info', :locals => {:version => version, :issues => version.sorted_fixed_issues, :totals => @totals} %>
  <%- else -%>
    <%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do -%>
      <%= render :partial => 'versions/info', :locals => {:version => version, :issues => version.sorted_fixed_issues, :totals => @totals} %>
    <% end %>
  <%- end -%>
  <%= call_hook :view_projects_roadmap_version_bottom, :version => version %>
<% end %>
</div>
<% end %>

<% content_for :sidebar do %>
<h3><%= label_milestone_plural %></h3>
<% @milestone.project.milestones.sort.each do |milestone| %>
<%= link_to milestone.name, :controller => :milestones, :action => :show, :id => milestone.id %><br />
<% end %>
<h3><%= l(:label_version_plural) %></h3>
<%= link_to(l(:label_total), '#total') %><br />
<% @milestone.versions.each do |version| %>
<%= link_to format_version_name(version), "##{version.name}" %><br />
<% end %>
<% end %>

<% html_title(l(:label_roadmap)) %>

<%- if Redmine::VERSION::STRING < '3.4.0' -%>
  <%= context_menu issues_context_menu_path %>
<%- else -%>
  <%= context_menu %>
<%- end -%>

<%= render :partial => 'common/advanced_roadmap_footer' %>

app/views/projects/settings/_milestones.html.erb
<% if @project.milestones.any? %>
<table class="list">
  <thead>
    <th style="text-align: left;"><%= label_milestone %></th>
    <th style="text-align: center;"><%= l(:field_effective_date) %></th>
    <th style="text-align: left;"><%= l(:field_description) %></th>
    <th style="text-align: center;"><%= l(:label_version_plural) %></th>
    <th style="width:15%"></th>
    <th style="width:15%"></th>
  </thead>
  <tbody>
  <% for milestone in @project.milestones.sort %>
    <tr class="<%= cycle 'odd', 'even' %>">
      <td style="text-align: left;">
        <%= link_to h(milestone.name), :controller => :milestones, :action => :show, :id => milestone.id %>
      </td>
      <td style="text-align: center;"><%= format_date(milestone.milestone_effective_date) %></td>
      <td style="text-align: left;"><%=h milestone.description %></td>
      <td style="text-align: center;">
        <%= milestone.versions.sort { |a, b|
              a.name.downcase <=> b.name.downcase
            }.collect { |v|
              link_to(h(v.name), :controller => :versions, :action => :show, :id => v)
            }.join(', ').html_safe %>
      </td>
      <td style="text-align: center;">
        <%- if User.current.allowed_to?(:manage_milestones, @project) -%>
          <%= link_to(l(:button_edit), edit_milestone_path(milestone),
                      :class => 'icon icon-edit') %>
        <%- end -%>
      </td>
      <td style="text-align: center;">
        <%- if User.current.allowed_to?(:manage_milestones, @project) -%>
          <%= delete_link(milestone_path(milestone)) %>
        <%- end -%>
      </td>
    </tr>
  <% end; reset_cycle %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<p><%= link_to l(:label_milestone_new, :milestone_label => label_milestone),
               new_project_milestone_path(@project, :back_url => ''),
               :class => 'icon icon-add' if User.current.allowed_to?(:manage_milestones, @project) %></p>

<%= javascript_tag do %>
  $('a#tab-milestones').text('<%= label_milestone_plural %>');
<% end %>

<%= render :partial => 'common/advanced_roadmap_footer' %>

app/views/settings/_advanced_roadmap_settings.html.erb
<%- defaults = Redmine::Plugin::registered_plugins[:advanced_roadmap].settings[:default] -%>

<%- version_custom_fields = CustomField.where(:type => 'VersionCustomField')
    version_custom_field_options = options_for_select([['', 0]] + version_custom_fields.collect{|c| [c.name, c.id]},
                                                      (@settings['parallel_effort_custom_field'] || defaults['parallel_effort_custom_field']).to_i) -%>

<p>
  <label><%= l(:label_setting_parallel_effort_custom_field) %>:</label>
  <%= select_tag('settings[parallel_effort_custom_field]', version_custom_field_options) %>
  <br />
  <em><%= l(:label_parallel_effort_hint) %></em>
</p>

<p>
  <label><%= l(:label_setting_solved_issues_to_estimate) %>:</label>
  <%= text_field_tag('settings[solved_issues_to_estimate]',
                     @settings['solved_issues_to_estimate'] || defaults['solved_issues_to_estimate']) %>
  <br />
  <em><%= l(:label_solved_issues_to_estimate_hint) %></em>
</p>

<hr />

<p>
  <!-- Formula image generated with:
         https://www.codecogs.com/latex/eqneditor.php
       Using formula:
         speed \ ratio = \frac{spent\ hours}{\ \ \frac{\ estimaged\ hours\ *\ done\ ratio\ }{100.0}\ \ }
       Direct URL to get the image:
         https://latex.codecogs.com/png.latex?\dpi{100}&space;\LARGE&space;speed&space;\&space;ratio&space;=&space;\frac{spent\&space;hours}{\&space;\&space;\frac{\&space;estimaged\&space;hours\&space;*\&space;done\&space;ratio\&space;}{100.0}\&space;\&space;}
       -->
  <%= image_tag('speed-ratio-formula.png', :plugin => 'advanced_roadmap') %><br />
  <em><%= l(:label_speed_ratio_hint) %></em>
</p>

<p>
  <label><%= l(:label_setting_ratio_good) %>:</label>
  <%= text_field_tag('settings[ratio_good]', @settings['ratio_good'] || defaults['ratio_good']) %>
</p>

<p>
  <label><%= l(:label_setting_color_good) %>:</label>
  <%= text_field_tag('settings[color_good]', @settings['color_good'] || defaults['color_good']) %>
</p>

<p>
  <label><%= l(:label_setting_ratio_bad) %>:</label>
  <%= text_field_tag('settings[ratio_bad]', @settings['ratio_bad'] || defaults['ratio_bad']) %>
</p>

<p>
  <label><%= l(:label_setting_color_bad) %>:</label>
  <%= text_field_tag('settings[color_bad]', @settings['color_bad'] || defaults['color_bad']) %>
</p>

<p>
  <label><%= l(:label_setting_ratio_very_bad) %>:</label>
  <%= text_field_tag('settings[ratio_very_bad]', @settings['ratio_very_bad'] || defaults['ratio_very_bad']) %>
</p>

<p>
  <label><%= l(:label_setting_color_very_bad) %>:</label>
  <%= text_field_tag('settings[color_very_bad]', @settings['color_very_bad'] || defaults['color_very_bad']) %>
</p>

<hr />

<p>
  <label><%= l(:label_setting_milestone_label) %>:</label>
  <%= text_field_tag('settings[milestone_label]', @settings['milestone_label'] || defaults['milestone_label']) %>
  <em><%= l(:label_setting_leave_emtpy_for_default) %></em>
</p>

<p>
  <label><%= l(:label_setting_milestone_plural_label) %>:</label>
  <%= text_field_tag('settings[milestone_plural_label]', @settings['milestone_plural_label'] || defaults['milestone_plural_label']) %>
  <em><%= l(:label_setting_leave_emtpy_for_default) %></em>
</p>

<%= render :partial => 'common/advanced_roadmap_footer' %>

app/views/versions/_total.html.erb
<div class="version-overview">
  <h3 class="icon22 icon22-package"><%= content_tag(:a, '', :name => 'total') %><%= l(:label_total) %></h3>
  <%- if true -%>
    <%= progress_bar([totals[:closed_pourcent], totals[:completed_pourcent]],
                     :titles => ["%s: %0.0f%%" % [l(:label_closed_issues_plural), totals[:closed_pourcent]],
                                 "%s: %0.0f%%" % [l(:field_done_ratio), totals[:completed_pourcent]]],
                     :legend => ('%0.0f%%' % totals[:completed_pourcent])) %>
    <p class="progress-info">
      <%= l(:label_x_issues, :count => totals[:issues_count]) %>
      &nbsp;
      (<%= l(:label_x_closed_issues_abbr, :count => totals[:closed_issues_count]) if totals[:closed_issues_count] > 0 %>
      &#8212;
      <%= l(:label_x_open_issues_abbr, :count => totals[:open_issues_count]) if totals[:open_issues_count] > 0 %>)
    </p>
  <%- else -%>
    <p class="progress-info"><%= l(:label_roadmap_no_issues) %></p>
  <%- end -%>
</div>
<br />

<fieldset><legend><%= l(:label_time_tracking) %></legend>
  <table width="100%">
    <tr>
      <td valign="top">
        <table>
        <%- if User.current.allowed_to?(:view_issue_estimated_hours, project) -%>
          <tr>
            <td width="300px" align="right"><%= l(:field_estimated_hours) %></td>
            <td width="340px" class="total-hours"><%= l_hours(totals[:estimated_hours]) %></td>
          </tr>
        <%- end -%>
        <%- if User.current.allowed_to?(:view_time_entries, project) -%>
          <tr>
            <td width="300px" align="right"><%= l(:label_spent_time) %></td>
            <td width="340px" class="total-hours"><%= l_hours(totals[:spent_hours]) %></td>
          </tr>
        <%- end -%>
        <tr>
          <td width="300px" align="right"><%= l(:field_done_ratio) %></td>
          <td width="340px" class="total-hours"><big><%= '%.0f' % totals[:completed_pourcent] %></big>%</td>
        </tr>
        <%- if User.current.allowed_to?(:view_time_entries, project) and
               User.current.allowed_to?(:view_issue_estimated_hours, project) -%>
          <tr>
            <td width="300px" align="right"><%= l(:label_roadmap_due_in, '') %></td>
            <td width="340px" class="total-hours"><%= "#{l_hours(totals[:rest_hours])} / #{l_days(totals[:rest_hours] / 8.0)} / #{l_weeks(totals[:rest_hours] / 40.0)}" %></td>
          </tr>
          <%- if totals[:rest_hours] != totals[:speed_rest_hours] -%>
            <tr>
              <td width="300px" align="right"><%= l(:label_roadmap_due_in, '') %> (<%= l(:label_estimated_speed) %>)</td>
              <td width="340px" class="total-hours"><%= "#{l_hours(totals[:speed_rest_hours])} / #{l_days(totals[:speed_rest_hours] / 8.0)} / #{l_weeks(totals[:speed_rest_hours] / 40.0)}" %></td>
            </tr>
          <%- end -%>
          <%- if !(custom_field = CustomField.find_by_id(AdvancedRoadmap::Setting.parallel_effort_custom_field)).nil? and
                 custom_field.field_format == 'float' and totals[:parallel_rest_hours] != totals[:rest_hours] -%>
            <tr>
              <td width="300px" align="right"><%= l(:label_roadmap_due_in, '') %> (<%= custom_field.name %>)</td>
              <td width="340px" class="total-hours"><%= "#{l_hours(totals[:parallel_rest_hours])} / #{l_days(totals[:parallel_rest_hours] / 8.0)} / #{l_weeks(totals[:parallel_rest_hours] / 40.0)}" %></td>
            </tr>
            <%- if totals[:parallel_rest_hours] != totals[:parallel_speed_rest_hours] -%>
              <tr>
                <td width="300px" align="right"><%= l(:label_roadmap_due_in, '') %> (<%= custom_field.name %> + <%= l(:label_estimated_speed) %>)</td>
                <td width="340px" class="total-hours"><%= "#{l_hours(totals[:parallel_speed_rest_hours])} / #{l_days(totals[:parallel_speed_rest_hours] / 8.0)} / #{l_weeks(totals[:parallel_speed_rest_hours] / 40.0)}" %></td>
              </tr>
            <%- end -%>
          <%- end -%>
          <%- estimated_due_date = Milestone.estimated_due_date(@totals) -%>
          <%- unless estimated_due_date.nil? -%>
            <tr>
              <td width="300px" align="right"><%= l(:label_estimated_due_date) %></td>
              <td width="340px" class="total-hours"><%= format_date(estimated_due_date) %></td>
            </tr>
          <%- end -%>
        <%- end -%>
        </table>
      </td>
      <td align="right">
        <%= total_graph_tag(versions, totals) %>
      </td>
    </tr>
  </table>
</fieldset>